# Generated by Django 4.2.6 on 2023-10-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_EasyNutri', '0002_alter_usuarios_cpf_alter_usuarios_telefone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
