# Generated by Django 4.2.6 on 2023-11-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_EasyNutri', '0004_pacientes_delete_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
    ]
