# Generated by Django 4.2.6 on 2023-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EasyNutri', '0005_rename_pacientes_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
