# Generated by Django 4.2.6 on 2023-10-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cpf', models.IntegerField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('conf_senha', models.CharField(max_length=30)),
            ],
        ),
    ]
